[package]
name = "chromiumoxide"
version = "0.1.0"
authors = ["Matthias Seitz <matthias.seitz@outlook.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/mattsse/chromiumoxide"
repository = "https://github.com/mattsse/chromiumoxide"
description = "Library for interacting with a chrome instance with the chrome devtools protocol"
keywords = ["chrome", "chromedriver", "puppeteer", "automation"]
categories = ["web-programming", "api-bindings", "development-tools::testing"]

[dependencies]
async-tungstenite = { version = "0.10", features = ["async-std-runtime"] }
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.6", features = ["attributes", "unstable"] }
anyhow = "1.0"
futures = "0.3"
chromiumoxide_types = { path = "chromiumoxide_types", version = "0.1.0" }
chromiumoxide_cdp = { path = "chromiumoxide_cdp", version = "0.1.0" }
serde_json = "1.0"
which = "4.0.2"
thiserror = "1.0.22"
url = "2.1.1"
tungstenite = "0.11.1"
log = "0.4.11"
base64 = "0.13.0"
fnv = "1.0.7"
futures-timer = "3.0.2"
pretty_env_logger = "0.4.0"

[dev-dependencies]
quote = "1.0"
proc-macro2 = "1.0"
chrono = "0.4"

[workspace]
members = [
    "chromiumoxide_pdl",
    "chromiumoxide_types",
    "chromiumoxide_cdp"
]
