[package]
name = "chromeoxid"
version = "0.1.0"
authors = ["Matthias Seitz <matthias.seitz@outlook.de>"]
edition = "2018"
license = "MIT OR APACHE-2.0"
readme = "README.md"
repository = "https://github.com/mattsse/chromeoxid"

[build-dependencies]
chromeoxid_pdl = { path = "chromeoxid_pdl", version = "0.1.0" }

[dependencies]
async-tungstenite = { version = "0.10", features = ["async-std-runtime"] }
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.6", features = ["attributes"] }
anyhow = "1.0"
regex = "1.4"
futures = "0.3"
chromeoxid_pdl = { path = "chromeoxid_pdl", version = "0.1.0" }
chromeoxid_types = { path = "chromeoxid_types", version = "0.1.0" }
serde_json = "1.0"
which = "4.0.2"
thiserror = "1.0.22"
url = "2.1.1"
tungstenite = "0.11.1"
bytes = "0.6.0"
log = "0.4.11"

[dev-dependencies]
quote = "1.0"
proc-macro2 = "1.0"
chrono = "0.4"

[features]
pdl = []

[workspace]
members = [
    "chromeoxid_pdl",
    "chromeoxid_types"
]
