[package]
name = "chromeoxid"
version = "0.1.0"
authors = ["mattsse <matthias.seitz@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tungstenite = "0.10.0"
serde = "1.0.117"
async-std = "1.6.5"
anyhow = "1.0.33"
regex = "1.4.1"

[dev-dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.24"
chrono = "0.4.19"
